baseURL = 'https://utspeech.github.io/'
languageCode = 'en-ca'
title = 'University of Toronto Speech Group'
theme = ['osm', 'hugo-cloak-email', 'beautifulhugo']

[taxonomies]
  speaker = 'speakers'

[Params]
  enableRobotsTXT = true
  defaultMeetingTime = '13:30'
  useHLJS = true
  mainSections = ['meetings']

[[menu.main]]
  name = 'Join Us'
  url = 'join'
  weight = 1

[[menu.main]]
  identifier = 'schedule'
  name = 'Schedule'
  weight = 2

[[menu.main]]
  parent = 'schedule'
  name = 'Fall 2022-Winter 2023'
  url = 'sched2022-2023'
  weight = 1

[[menu.main]]
  name = 'Archive'
  url = 'meetings'
  weight = 3

[[menu.main]]
  name = 'Speakers'
  url = 'speakers'
  weight = 4
