baseURL = 'https://utspeech.github.io/'
languageCode = 'en-ca'
title = 'University of Toronto Speech Group'
theme = ['osm', 'hugo-cloak-email', 'beautifulhugo']

[taxonomies]
  speaker = 'speakers'

[Params]
  enableRobotsTXT = true
  defaultMeetingTime = "13:30"
  useHLJS = true
  mainSections = ['meetings']

[[menu.main]]
  name = 'Join Us'
  url = 'join'

[[menu.main]]
  name = 'Meetings'
  url = 'meetings'

[[menu.main]]
  name = 'Speakers'
  url = 'speakers'
